use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CritiqueResult {
    pub correctness: u32,        // 1-5
    pub completeness: u32,        // 1-5
    pub style: u32,              // 1-5
    pub security: u32,           // 1-5
    pub overall: String,         // YES / NEEDS_REFINEMENT / NO
    pub issues: Vec<String>,
}

pub fn self_critique_prompt(task: &str, code: &str) -> String {
    format!(
        r#"You are reviewing code generated by a junior developer. Be strict but fair.

TASK: {}
GENERATED CODE:
{}

Score each dimension 1-5:
- Correctness: Does it solve the stated task?
- Completeness: Are edge cases handled?
- Style: Does it follow the project's conventions?
- Security: Any obvious vulnerabilities?

OVERALL: Would you ship this? (YES / NEEDS_REFINEMENT / NO)
If NEEDS_REFINEMENT or NO, list the specific issues to fix.
Respond in JSON only with fields: {{correctness, completeness, style, security, overall, issues}}
"#,
        task, code
    )
}

pub fn parse_critique(json_str: &str) -> Option<CritiqueResult> {
    serde_json::from_str::<CritiqueResult>(json_str).ok()
}
